[features]
seeds = false
skip-lint = false
[programs.devnet]
nftwalletbridge = "CcyvqjwZWKsQuLXjdKsx3BA7BqnAKonrXdZVMDPy7pXG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/junyang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
